# 对象初始化和发布时的安全问题

## 什么是发布

把对象让超过这个类范围之内的类使用，比如 public，一个对象被声明为 public，它就是被发布出去了；

方法的返回值，如果一个方法返回值是一个对象，那么这个对象也被发布出去了；方法的参数如果是一个对象，那么此对象也是被发布出去的。

## 什么是逸出

含义：发布到了不该发布的地方（发布的不好）

1. 方法返回一个 private 对象（private 本意是不让外部访问）
2. 还未完成初始化（构造函数没完全执行完毕）就把对象提供给外界：
   * 在构造函数中未初始化完毕就给 this 赋值
   * 隐式逸出-注册器监听
   * 构造函数中运行线程



## 方法返回一个 private 对象

方法返回一个 private 对象本身没有错，但有些错误做法会引发线程安全问题，代码演示：

```java
package threadcoreknowledge.multithreaderror;

import java.util.HashMap;
import java.util.Map;
import java.util.logging.Logger;

/**
 * 演示：返回的 private 对象被修改了
 * @author mfh
 * @date 2020/5/10 23:20
 */
public class MultiThreadErrorReturnPrivateObj {
    private final Map<Integer, String> week;

    public MultiThreadErrorReturnPrivateObj() {
        week = new HashMap<>();
        week.put(1, "周一");
        week.put(2, "周二");
        week.put(3, "周三");
        week.put(4, "周四");
    }

    public Map<Integer, String> getWeek() {
        return week;
    }
    
    public static void main(String[] args) {
        Logger logger = Logger.getAnonymousLogger();
        MultiThreadErrorReturnPrivateObj m = new MultiThreadErrorReturnPrivateObj();
        Map<Integer, String> yesterday = m.getWeek();
        logger.info(yesterday.get(1));
        yesterday.remove(1);
        Map<Integer, String> today = m.getWeek();
        logger.info(today.get(1));
    }
}
```

结果：

```java
五月 10, 2020 11:30:20 下午 threadcoreknowledge.multithreaderror.MultiThreadErrorReturnPrivateObj main
信息: 周一
五月 10, 2020 11:30:20 下午 threadcoreknowledge.multithreaderror.MultiThreadErrorReturnPrivateObj main
信息: null
```

week 里面保存的星期，本意 week 是不能被修改的，但确实是被修改了，这样获取到的数据就不一致了，有可能昨天调用`week.get(1)`的时候还是`周一`，但是今天就返回了`null`，这样的程序是不稳定的。解决方式：采用返回副本的形式。

```java
package threadcoreknowledge.multithreaderror;

import java.util.HashMap;
import java.util.Map;
import java.util.logging.Logger;

/**
 * 演示：返回的 private 对象被修改了
 * @author mfh
 * @date 2020/5/10 23:20
 */
public class MultiThreadErrorReturnPrivateObj {
    private final Map<Integer, String> week;

    public MultiThreadErrorReturnPrivateObj() {
        week = new HashMap<>();
        week.put(1, "周一");
        week.put(2, "周二");
        week.put(3, "周三");
        week.put(4, "周四");
    }

    public Map<Integer, String> getWeek() {
        // 返回副本
        return new HashMap<>(week);
    }
    
    public static void main(String[] args) {
        Logger logger = Logger.getAnonymousLogger();
        MultiThreadErrorReturnPrivateObj m = new MultiThreadErrorReturnPrivateObj();
        Map<Integer, String> yesterday = m.getWeek();
        logger.info(yesterday.get(1));
        yesterday.remove(1);
        Map<Integer, String> today = m.getWeek();
        logger.info(today.get(1));
    }
}

```

```java
五月 10, 2020 11:31:06 下午 threadcoreknowledge.multithreaderror.MultiThreadErrorReturnPrivateObj main
信息: 周一
五月 10, 2020 11:31:06 下午 threadcoreknowledge.multithreaderror.MultiThreadErrorReturnPrivateObj main
信息: 周一
```

返回副本后，无论是昨天还是今天，获取的结果都是`周一`。

## 在构造函数中未初始化完毕就给 this 赋值

创建 Point 的工作是由另一个线程完成的。

```java
package threadcoreknowledge.multithreaderror;

/**
 * 演示：在构造函数中未初始化完毕就给 this 赋值
 * @author mfh
 * @date 2020/5/10 23:34
 */
public class MultiThreadError1 {
    static Point point;

    public static void main(String[] args) throws InterruptedException {
        new PointMaker().start();
        // 休眠10毫秒	
        Thread.sleep(10);
        System.out.println(point);
    }
}

class Point {
    private final int x;
    private final int y;

    public Point(int x, int y) throws InterruptedException {
        this.x = x;
        MultiThreadError1.point = this;
        Thread.sleep(100);
        this.y = y;
    }

    @Override
    public String toString() {
        return "Point{" +
                "x=" + x +
                ", y=" + y +
                '}';
    }
}

class PointMaker extends Thread {
    @Override
    public void run() {
        try {
            new Point(1,1);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}
```

结果：

```java
Point{x=1, y=0}
```

把休眠 10 毫秒改为休眠 105 毫秒，再看结果：

```java
Point{x=1, y=1}
```

休眠 10 毫秒，Point 的初始化操作还没有完成，y 还没有被赋值，所以 y 等于 0，但当休眠 105 毫秒时，Point 初始化完毕了，y 完成了赋值，所以 y 等于 1。

这样的程序也是不稳定的，这就是在构造函数中未初始化完毕就给 this 赋值带来的后果。

以上这种错误写法比较明显，只要在构造函数中提前把 this 赋值就可以了。但是下面这种情况就不比较隐式了。

## 隐式逸出-注册监听器

代码如下：

```java
package threadcoreknowledge.multithreaderror;

import java.util.concurrent.TimeUnit;

/**
 * 描述：观察者模式
 *
 * @author mfh
 * @date 2020/5/11 21:35
 */
public class MultiThreadError2 {
    int count;

    public MultiThreadError2(MySource mySource) {
        mySource.registerListener((e) -> System.out.printf("\n我得到的数字是%d\n", count));
        for (int i = 0; i < 1000; i++) {
            System.out.print(i);
        }
        count = 100;
    }

    public static void main(String[] args) {
        MySource source = new MySource();
        new Thread(() -> {
            try {
                TimeUnit.MILLISECONDS.sleep(10);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            source.eventCome(new Event() {
            });

        }).start();
        MultiThreadError2 me2 = new MultiThreadError2(source);
    }

    static class MySource {
        private EventListener listener;

        void registerListener(EventListener listener) {
            this.listener = listener;
        }

        void eventCome(Event event) {
            if (listener != null) {
                listener.onEvent(event);
            } else {
                System.out.println("还未初始化完毕");
            }
        }
    }

    interface EventListener {
        void onEvent(Event event);
    }

    interface Event {
    }
}
```

结果：

```java
712713714715716717718719720721722723724725726727728729730731732733734735736737738739740741742743744745746747748749750751752753754755756757758759760761762763764765766767768769770
我得到的数字是0
771772773774775776777778779780781782783784785786787788789790791792793794795796797798799800801802803804805806807808809810811812813814815816817818819820821822823824825826827828829830831832833834835836837838839840841842843844845846847848849850851852853854855856857858859860861862863864865866867868869870871872873874875876877878879880881882883884885886887888889890891892893894895896897898899900901902903904905906907908909910911912913914915916917918919920921922923924925926927928929930931932933934935936937938939940941942943944945946947948949950951952953954955956957958959960961962963964965966967968969970971972973974975976977978979980981982983984985986987988989990991992993994995996997998999
```

明明在构造函数中已经将 count 赋值了 100，为什么这里会打印 0。

分析：

在构造函数中只是注册了监听器，当监听器运行时，count 还没有被赋成 100，所以打印 0。匿名内部类持有外部类的引用，可以操作 count 值，这也是一种逸出。（个人感觉这个例子好傻，没有让我觉得眼前一亮，就不继续分析了）

解决方案：

使用工厂模式解决这个问题，代码如下：

```java
package threadcoreknowledge.multithreaderror;

import java.util.concurrent.TimeUnit;

/**
 * 描述：使用工厂模式修复 MultiThreadError2 的问题
 * 思路：
 * 1.构造私有化
 * 2.使用 getInstance 方法去创建对象，使得构造函数完全结束后，再返回对象
 * @author mfh
 * @date 2020/5/11 21:35
 */
public class MultiThreadError2FixByFactoryPattern {
    int count;
    private EventListener listener;
    private MultiThreadError2FixByFactoryPattern() {
        listener = (e) -> System.out.printf("\n我得到的数字是%d\n", count);
        for (int i = 0; i < 1000; i++) {
            System.out.print(i);
        }
        count = 100;
    }

    public static MultiThreadError2FixByFactoryPattern getInstance(MySource source) {
        MultiThreadError2FixByFactoryPattern fix = new MultiThreadError2FixByFactoryPattern();
        source.registerListener(fix.listener);
        return fix;
    }

    public static void main(String[] args) {
        MySource source = new MySource();
        new Thread(() -> {
            try {
                TimeUnit.MILLISECONDS.sleep(10);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            source.eventCome(new Event() {
            });

        }).start();
        MultiThreadError2FixByFactoryPattern.getInstance(source);
    }

    static class MySource {
        private EventListener listener;

        void registerListener(EventListener listener) {
            this.listener = listener;
        }

        void eventCome(Event event) {
            if (listener != null) {
                listener.onEvent(event);
            } else {
                System.out.println("还未初始化完毕");
            }
        }
    }

    interface EventListener {
        void onEvent(Event event);
    }

    interface Event {
    }
}
```

## 构造函数中运行线程

```java
package threadcoreknowledge.multithreaderror;

import java.util.HashMap;
import java.util.Map;
import java.util.logging.Logger;

/**
 * 演示：在构造函数中开启新的线程，这样做也会有问题。
 * @author mfh
 * @date 2020/5/10 23:20
 */
public class MultiThreadErrorNewThreadInConstructor {
    private Map<Integer, String> week;

    public MultiThreadErrorNewThreadInConstructor() {
        new Thread(() -> {
            week = new HashMap<>();
            week.put(1, "周一");
            week.put(2, "周二");
            week.put(3, "周三");
            week.put(4, "周四");
        }).start();
    }

    public Map<Integer, String> getWeek() {
        // 返回副本
        return new HashMap<>(week);
    }
    
    public static void main(String[] args) {
        Logger logger = Logger.getAnonymousLogger();
        MultiThreadErrorNewThreadInConstructor m = new MultiThreadErrorNewThreadInConstructor();
        Map<Integer, String> yesterday = m.getWeek();
        logger.info(yesterday.get(1));
        yesterday.remove(1);
        Map<Integer, String> today = m.getWeek();
        logger.info(today.get(1));
    }
}
```

结果：

```java
Exception in thread "main" java.lang.NullPointerException
	at java.util.HashMap.putMapEntries(HashMap.java:501)
	at java.util.HashMap.<init>(HashMap.java:490)
	at threadcoreknowledge.multithreaderror.MultiThreadErrorNewThreadInConstructor.getWeek(MultiThreadErrorNewThreadInConstructor.java:27)
	at threadcoreknowledge.multithreaderror.MultiThreadErrorNewThreadInConstructor.main(MultiThreadErrorNewThreadInConstructor.java:33)
```

此时会有空指针异常。

让主线程休眠一会：

```java
public static void main(String[] args) throws InterruptedException {
    Logger logger = Logger.getAnonymousLogger();
    MultiThreadErrorNewThreadInConstructor m = new MultiThreadErrorNewThreadInConstructor();
    // 主线程休眠一会
    Thread.sleep(100);
    Map<Integer, String> yesterday = m.getWeek();
    logger.info(yesterday.get(1));
    yesterday.remove(1);
    Map<Integer, String> today = m.getWeek();
    logger.info(today.get(1));
}
```

结果：

```java
五月 11, 2020 10:17:20 下午 threadcoreknowledge.multithreaderror.MultiThreadErrorNewThreadInConstructor main
信息: 周一
五月 11, 2020 10:17:20 下午 threadcoreknowledge.multithreaderror.MultiThreadErrorNewThreadInConstructor main
信息: 周一
```

空指针异常神奇的不见了。程序随着时间的不同，产生的结果不一样，这对程序的稳定性是一种很严重的打击。

这个例子演示的代码或许我们在实际工作开发中不会犯这个错误，也就是我们不会在构造函数中新开现场，但有的时候是我们不经意间操作的。比如数据库连接操作，我们有可能会在构造函数中获取连接，新建连接的操作很有可能就是由另一个线程执行的，只是我们不知道，所以也相当于是在构造函数中新开了线程，只是我们不知道而已。

## 各种需要考虑线程安全的情况

1. 访问共享的变量或者资源，会有并发风险，比如对象的属性、静态变量、共享缓存、数据库等。

   1. 典型的 index++ 操作

2. 所以依赖时序的操作，即使每一步操作都是现场安全的，还是存在并发问题：read-modify-write、check-then-act

   1. 先读取，再修改
   2. 先检查，在执行

   一个线程去读取一个东西，然后根据读取的结果决定下一步的事情，这样也许会有问题，当你读取完成后，很有可能在被别人去修改。所以在依赖时序的情况下，要注意线程安全的问题。可以使用 synchronized 把它们作为一个原子操作绑定起来，就可以解决这样的问题。

3. 不同的数据之间存在捆绑关系的时候。

   1. ip 与端口号，它们是相对应的，单独拿出来一个是没哟意义的，是要求成对出现的。所以，凡是这种存在捆绑关系的数据时，要考虑线程安全问题。

4. 我们使用其他类的时候，如果对方没有声明自己是线程安全的。

   1. 比如 HashMap 就声明了自己不是线程安全的，所以我们在高并发的场景下就使用 ConcurrentHashMap
   2. 在使用对方服务的时候，自己要把关，看看使用的服务是否是线程安全的，如果不能就不要使用，或者自己做出处理，保证其线程安全。

## 性能问题

### 性能问题有哪些，什么是性能问题

1. 服务响应慢，吞吐量低，资源消耗（例如内存）过高
2. 显然不是结果错误，但依然危害巨大
3. 引入多线程不能本末倒置

## 为什么多线程会带来性能问题 

### 调度：上下文切换

#### 什么是上下文切换

​	上下文切换可以认为是内核（操作系统的核心）在 CPU 上对于进程（包括线程）进行一下活动：

1. 挂起一个进程，将这个进程在 CPU 中的状态（上下文）存储于内存中的某处。
2. 在内存中检索下一个进程的上下文并在其 CPU 的寄存器中恢复。
3. 跳转到程序计数器所指向的位置（即跳转到进程被中断时的代码行），以恢复该进程。

#### 缓存开销

CPU 重新缓存，由于上下文切换，导致大量缓存失效，所以 CPU 还有重新缓存数据

#### 何时会导致密集的上下文切换

频繁的竞争锁，或者由于 IO 读写等原因导致频繁阻塞

### 协作：内存同步

#### Java 内存模型

为了数据的正确性，同步手段往往会使用禁止编译器优化，使 CPU 内缓存失效

## 常见面试问题

* 有哪些线程不安全的情况
* 平时哪些情况需要额外注意线程安全问题
* 什么是多线程上下文切换