# 线程安全

## 什么是线程安全

### Brian Goetz 的定义

《Java Concurrency In Practice》的作者 Brian Goetz 对“线程安全”有一个比较恰当的定义：“当多个线程访问一个对象时，如果<font color=red>**不用考虑**</font>这些线程在运行时环境下的调度和交替执行，<font color=red>**也不需要进行额外的同步**</font>，或者在调用方进行任何其他的协调操作，调用这个对象的行为都可以获得<font color=red>**正确的结果**</font>，那这个对象就是线程安全的。”

### 悟空的定义

不管业务中遇到怎样的多个线程访问某个对象或某方法的情况，而在编程这个业务逻辑的时候，<font color=red>**都不需要额外做任何额外的处理**</font>（也就是可以像单线程编程一样），程序也可以正常运行（不会因为多线程而出错），就可以称为线程安全。

* 线程不安全
  * get 同时 set，额外同步，这些表现都说明线程是不安全的，如果线程安全就不需要额外的同步了
* 全都线程安全
  * 全部都设计成线程安全的，那么程序的运行速度会受到影响，而且设计成本会增高
* 完全不用于多线程
  * 如果一个类在设计的时候就能知道，它完全不会用于多线程，那么就不需要考虑线程安全问题，不要过度设计

## 什么情况下会出现线程安全问题，怎么避免？

### 运行结果错误：a++ 多线程下出现消失的请求现象

#### 错误浮出水面

index 分别由两个线程做 ++ 操作，每个线程循环 10000 次，最后 index 应该是 20000，但结果与实际不符，代码如下：

```java
package threadcoreknowledge.multithreaderror;

/**
 * 运行结果出错
 * 演示计数不准确（减少），找出出错的位置。
 *
 * @author mfh
 * @date 2020/5/5 11:27
 */
public class MultiThreadError implements Runnable {
    final static MultiThreadError multiThreadError = new MultiThreadError();
    int index;
    @Override
    public void run() {
        for (int i = 0; i < 10000; i++) {
            index++;
        }
    }

    public static void main(String[] args) throws InterruptedException {
        Thread t0 = new Thread(multiThreadError);
        Thread t1 = new Thread(multiThreadError);
        t0.start();
        t1.start();
        t0.join();
        t1.join();
        System.out.println("表面上的结果，num：" + multiThreadError.index);
    }
}
```

结果：

```java
表面上的结果，num：16774
```

发生错误的原因：由于 index++ 并不是一次原子性操作，它实际分为三步操作：

1、从内存中把i的值取出来放到CPU的寄存器中

2、CPU寄存器的值+1

3、把CPU寄存器的值写回内存

在并发情况下，这种操作会有线程安全问题，所以就出现了上面错误的结果。下面我们来统计一下错误的次数，看看是哪一次发生了线程冲突。

#### 统计错误次数

##### 第一次尝试

思路：使用 boolean 数组，采用标记的方式统计错误次数

```java
package threadcoreknowledge.multithreaderror;

import java.util.concurrent.atomic.AtomicInteger;

/**
 * 运行结果出错
 * 演示计数不准确（减少），找出出错的位置。
 *
 * @author mfh
 * @date 2020/5/5 11:27
 */
public class MultiThreadError implements Runnable {
    final static MultiThreadError multiThreadError = new MultiThreadError();
    int index;
    boolean[] marked = new boolean[1000000];
    @Override
    public void run() {
        for (int i = 0; i < 10000; i++) {
            index++;
            if (marked[index]) {
                System.out.println("线程冲突，错误 index：" + index);
            }
            /**
             *  当某一个线程将此索引标记为 true，如果正常的情况，下一个线程进来应该执行 index++，
             *  if 判断肯定为 false，因为正常情况下，赋值 true 是在 if 下面，如果上面的 if
             *  条件成立，则说明两个线程同时操作了 index
             */
            marked[index] = true;
        }
    }

    public static void main(String[] args) throws InterruptedException {
        Thread t0 = new Thread(multiThreadError);
        Thread t1 = new Thread(multiThreadError);
        t0.start();
        t1.start();
        t0.join();
        t1.join();
        System.out.println("表面上的结果，num：" + multiThreadError.index);
    }
}

```

结果：

```java
线程冲突，错误 index：2658
线程冲突，错误 index：9289
表面上的结果，num：19993
```

观察以上结果，展示的数值并不能清晰的统计次数，我们加上总共执行次数与错误次数。因为存在线程安全问题，所以统计次数的变量类型使用 AtomicInteger。

##### 第二次尝试

```java
package threadcoreknowledge.multithreaderror;

import java.util.concurrent.atomic.AtomicInteger;

/**
 * 运行结果出错
 * 演示计数不准确（减少），找出出错的位置。
 *
 * @author mfh
 * @date 2020/5/5 11:27
 */
public class MultiThreadError implements Runnable {
    final static MultiThreadError multiThreadError = new MultiThreadError();
    int index;
    boolean[] marked = new boolean[1000000];
    /* 实际运行次数 */
    static AtomicInteger total = new AtomicInteger();
    /* 错误次数 */
    static AtomicInteger wrongCount = new AtomicInteger();
    @Override
    public void run() {
        for (int i = 0; i < 10000; i++) {
            total.incrementAndGet();
            index++;
            if (marked[index]) {
                wrongCount.incrementAndGet();
                System.out.println("线程冲突，错误 index：" + index);
            }
            /**
             *  当某一个线程将此索引标记为 true，如果正常的情况，下一个线程进来应该执行 index++，
             *  if 判断肯定为 false，因为正常情况下，赋值 true 是在 if 下面，如果上面的 if
             *  条件成立，则说明两个线程同时操作了 index
             */
            marked[index] = true;
        }
    }

    public static void main(String[] args) throws InterruptedException {
        Thread t0 = new Thread(multiThreadError);
        Thread t1 = new Thread(multiThreadError);
        t0.start();
        t1.start();
        t0.join();
        t1.join();
        System.out.println("表面上的结果，num：" + multiThreadError.index);
        System.out.println("一共实际执行的次数：" + total.get());
        System.out.println("发生错误次数：" + wrongCount.get());
    }
}
```

结果：

 ```java
线程冲突，错误 index：2638
线程冲突，错误 index：10361
表面上的结果，num：19992
一共实际执行的次数：20000
发生错误次数：2
 ```

观察以上结果，正常情况下，`表面运行次数 + 发生错误次数 = 一共实际执行次数`，但实际结果又是不符合预期的。分析原因：

当 t0 准备执行（注意是准备执行） `if(marked[index]){}` 时，就在这一时刻，t1 获得了时间片，执行`marked[index] = true`，然后 t0 又获取到了时间片，执行 `if(marked[index]){}`，此时数组索引 index 位置的值就变成了 true，这明显不符合 t0 的预期，t0 执行的数组索引 index 位置本来是 false。这样统计的结果由于线程冲突，肯定是不准确的。

##### 第三次尝试

根据以上分析，在判断的与赋值的地方加 synchronized 同步代码块，修改代码如下：

```java
synchronized (wrongCount) {
    if (marked[index]) {
        wrongCount.incrementAndGet();
        System.out.println("线程冲突，错误 index：" + index);
    }
    /**
      *  当某一个线程将此索引标记为 true，如果正常的情况，下一个线程进来应该执行 index++，
      *  if 判断肯定为 false，因为正常情况下，赋值 true 是在 if 下面，如果上面的 if
      *  条件成立，则说明两个线程同时操作了 index
      */
    marked[index] = true;
}
```

完整代码如下：

```java
package threadcoreknowledge.multithreaderror;

import java.util.concurrent.atomic.AtomicInteger;

/**
 * 运行结果出错
 * 演示计数不准确（减少），找出出错的位置。
 *
 * @author mfh
 * @date 2020/5/5 11:27
 */
public class MultiThreadError implements Runnable {
    final static MultiThreadError multiThreadError = new MultiThreadError();
    int index;
    boolean[] marked = new boolean[1000000];
    /* 实际运行次数 */
    static AtomicInteger total = new AtomicInteger();
    /* 错误次数 */
    static AtomicInteger wrongCount = new AtomicInteger();
    @Override
    public void run() {
        for (int i = 0; i < 10000; i++) {
            total.incrementAndGet();
            index++;
            synchronized (multiThreadError) {
                if (marked[index]) {
                    wrongCount.incrementAndGet();
                    System.out.println("线程冲突，错误 index：" + index);
                }
                /**
                 *  当某一个线程将此索引标记为 true，如果正常的情况，下一个线程进来应该执行 index++，
                 *  if 判断肯定为 false，因为正常情况下，赋值 true 是在 if 下面，如果上面的 if
                 *  条件成立，则说明两个线程同时操作了 index
                 */
                marked[index] = true;
            }
        }
    }

    public static void main(String[] args) throws InterruptedException {
        Thread t0 = new Thread(multiThreadError);
        Thread t1 = new Thread(multiThreadError);
        t0.start();
        t1.start();
        t0.join();
        t1.join();
        System.out.println("表面上的结果，num：" + multiThreadError.index);
        System.out.println("一共实际执行的次数：" + total.get());
        System.out.println("发生错误次数：" + wrongCount.get());
    }
}
```

结果：

```java
线程冲突，错误 index：111
线程冲突，错误 index：246
线程冲突，错误 index：247
线程冲突，错误 index：360
线程冲突，错误 index：1082
线程冲突，错误 index：1218
线程冲突，错误 index：2110
线程冲突，错误 index：2301
线程冲突，错误 index：2527
线程冲突，错误 index：2714
线程冲突，错误 index：2874
线程冲突，错误 index：3466
线程冲突，错误 index：3689
线程冲突，错误 index：3823
线程冲突，错误 index：4039
线程冲突，错误 index：4144
线程冲突，错误 index：4332
线程冲突，错误 index：4473
线程冲突，错误 index：4621
线程冲突，错误 index：4809
线程冲突，错误 index：4936
线程冲突，错误 index：5138
线程冲突，错误 index：5354
线程冲突，错误 index：5542
线程冲突，错误 index：8223
线程冲突，错误 index：8379
线程冲突，错误 index：8589
线程冲突，错误 index：8716
线程冲突，错误 index：8857
线程冲突，错误 index：9003
线程冲突，错误 index：9210
线程冲突，错误 index：9327
线程冲突，错误 index：9491
线程冲突，错误 index：9685
线程冲突，错误 index：9824
线程冲突，错误 index：9938
线程冲突，错误 index：10036
表面上的结果，num：20000
一共实际执行的次数：20000
发生错误次数：37
```

观察以上结果，更加匪夷所思。继续分析原因：

也许有人会说，直接把 index++ 也放入同步代码块不就没有问题了吗？这是正确的做法，但这种做法与我们要做的事情就背道而驰了，我们现在要做的是统计错误的次数，就是要让它出错，你现在把 index++ 放入同步代码块，就不会出错了，也就不会统计到错误次数了。我们现在就是要让他出错，但现在要解决的问题是，在要他出错的这条路上，有一些不应该有的错误，正是因为有这些错误，使我们不能得到预期的结果，所以我们现在要解决这些错误。

继续分析原因：

当 t0 准备执行（注意是准备执行） `if(marked[index]){}` 时（index 等于 1），t1 执行了 index++，此时要判断的数组索引 index 位置就发生了变化，这是不对的，下面解决这个问题。

##### 第四次尝试

我们加入 CyclicBarrier 来拦截 t0，t1 这两个线程，使其都到位了才开始执行下面的 index++ 操作，注意，只在 index++ 上面加了 CyclicBarrier 拦截是不够的。因为，当两个线程都到位后，t0 线程被分配的 cpu 时间片多，所以它执行的快，t0 先执行了 index++，t0 首先执行到了`if (marked[index])P{}`，此时 t1 获取到了 cpu 时间片，然后 t1 开始执行 index++，然后又调度回来 t0 开始执行判断，此时 index 的值又是不正确的。所以需要在 index++ 之后也加入 CyclicBarrier 拦截。这样不但可以复现由于线程冲突造成对于 index 值错误的累加效果，又可以保证，这种累加效果不会影响到统计错误次数的判断。

```java
package threadcoreknowledge.multithreaderror;

import java.util.concurrent.BrokenBarrierException;
import java.util.concurrent.CyclicBarrier;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * 运行结果出错
 * 演示计数不准确（减少），找出出错的位置。
 *
 * @author mfh
 * @date 2020/5/5 11:27
 */
public class MultiThreadError implements Runnable {
    final static MultiThreadError multiThreadError = new MultiThreadError();
    int index;
    boolean[] marked = new boolean[1000000];
    /* 实际运行次数 */
    static AtomicInteger total = new AtomicInteger();
    /* 错误次数 */
    static AtomicInteger wrongCount = new AtomicInteger();
    CyclicBarrier cyclicBarrier0 = new CyclicBarrier(2);
    CyclicBarrier cyclicBarrier1 = new CyclicBarrier(2);
    @Override
    public void run() {
        for (int i = 0; i < 10000; i++) {
            total.incrementAndGet();
            try {
                cyclicBarrier1.reset();
                /** 等待 t0、t1 都到位了才开始执行 */
                cyclicBarrier0.await();
            } catch (InterruptedException e) {
                e.printStackTrace();
            } catch (BrokenBarrierException e) {
                e.printStackTrace();
            }
            index++;
            try {
                cyclicBarrier0.reset();
                /** 等到都执行完了 index++ 才开始执行 */
                cyclicBarrier1.await();
            } catch (InterruptedException e) {
                e.printStackTrace();
            } catch (BrokenBarrierException e) {
                e.printStackTrace();
            }
            synchronized (multiThreadError) {
                if (marked[index]) {
                    wrongCount.incrementAndGet();
                    System.out.println("线程冲突，错误 index：" + index);
                }
                /**
                 *  当某一个线程将此索引标记为 true，如果正常的情况，下一个线程进来应该执行 index++，
                 *  if 判断肯定为 false，因为正常情况下，赋值 true 是在 if 下面，如果上面的 if
                 *  条件成立，则说明两个线程同时操作了 index
                 */
                marked[index] = true;
            }
        }
    }

    public static void main(String[] args) throws InterruptedException {
        Thread t0 = new Thread(multiThreadError);
        Thread t1 = new Thread(multiThreadError);
        t0.start();
        t1.start();
        t0.join();
        t1.join();
        System.out.println("表面上的结果，num：" + multiThreadError.index);
        System.out.println("一共实际执行的次数：" + total.get());
        System.out.println("发生错误次数：" + wrongCount.get());
    }
}

```

结果

```java
线程冲突，错误 index：19929
线程冲突，错误 index：19931
线程冲突，错误 index：19933
线程冲突，错误 index：19935
线程冲突，错误 index：19937
线程冲突，错误 index：19939
线程冲突，错误 index：19941
线程冲突，错误 index：19943
线程冲突，错误 index：19945
线程冲突，错误 index：19947
线程冲突，错误 index：19949
线程冲突，错误 index：19951
线程冲突，错误 index：19953
线程冲突，错误 index：19955
线程冲突，错误 index：19957
线程冲突，错误 index：19959
线程冲突，错误 index：19961
线程冲突，错误 index：19963
线程冲突，错误 index：19965
线程冲突，错误 index：19967
线程冲突，错误 index：19969
线程冲突，错误 index：19971
线程冲突，错误 index：19973
线程冲突，错误 index：19975
线程冲突，错误 index：19977
线程冲突，错误 index：19979
线程冲突，错误 index：19981
线程冲突，错误 index：19983
线程冲突，错误 index：19985
线程冲突，错误 index：19987
线程冲突，错误 index：19989
线程冲突，错误 index：19991
线程冲突，错误 index：19993
线程冲突，错误 index：19995
线程冲突，错误 index：19997
线程冲突，错误 index：19999
表面上的结果，num：19999
一共实际执行的次数：20000
发生错误次数：10000
```

观察以上结果，还是不对啊，是不是快崩溃了，别着急，马上见分晓。

我们再分析一次：

观察以上结果，发现线程冲突的错误 index 是有规律的，比如 19975、19977、19979，都是两个两个往上增加。因为 index++ 被两个线程执行的结果，比如 index 等于 19975，t0 执行 index++，index 变成 19976，CyclicBarrier 会等到两个线程都执行完毕才会继续执行，所以 t1 执行 index++，index 变成了 19977，然后 t1 继续执行，执行到`if (marked[index])`时，条件不成立所以跳过，执行`marked[index] = true`，执行完之后，数组索引 19977 位置的值变成 true，然后 t0 释放锁，t1 开始执行，执行到`if (marked[index])`时，条件成立，所以记录了错误次数并输出线程冲突....。其实这样是不对的，这并不是错误，而是由于 synchronized 的内存可见性，使得 t0 修改完 index 之后，index 的值对 t1 是可见的，所以才会发生这个问题，这并不是错误。问题是出在了判断逻辑上，所以我们要修改`if (marked[index])` 判断逻辑，改为`if (marked[index] && marked[index - 1])`才是正确的判断。不光是当前索引处值为 true，前一个索引处的值也应该是 true 才算错误。想一下，t0 执行 index++，index 值加1，然后 t1 执行 index++，index 值加1，index 增量 2 这是正常的，并没有发生冲突，那么怎么才算冲突呢？应该是 t0 执行 index++ 的同时 t1 也执行 index++，index 的增量是 1 的时候（执行了两次，但 index 只增加了 1），这才是由于线程冲突造成的结果。

还需要考虑一点：

index 从 0 开始，index++ 之后变成 1（marked[0] 永远也没机会变成 true），如果两个线程正好在这里冲突，即 t0 执行 index++ 的同时 t1 也执行 index++，执行完之后，由于冲突，index 的结果是 1，这是错误的，需要统计。当执行任意线程执行`if (marked[index] && marked[index - 1])`时，`marked[index - 1]`是 false，条件不成立，不会记录错误，这样就会少记录一次错误的情况。所以需要在开头就把 marked[0] 赋值为 true，即把`marked[index - 1]`的值手动赋为 true 。这样，一旦有了上面的错误，也能正常统计了。

##### 第五次尝试

```java
package threadcoreknowledge.multithreaderror;

import java.util.concurrent.BrokenBarrierException;
import java.util.concurrent.CyclicBarrier;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * 运行结果出错
 * 演示计数不准确（减少），找出出错的位置。
 *
 * @author mfh
 * @date 2020/5/5 11:27
 */
public class MultiThreadError implements Runnable {
    final static MultiThreadError multiThreadError = new MultiThreadError();
    int index;
    boolean[] marked = new boolean[1000000];
    /* 实际运行次数 */
    static AtomicInteger total = new AtomicInteger();
    /* 错误次数 */
    static AtomicInteger wrongCount = new AtomicInteger();
    CyclicBarrier cyclicBarrier0 = new CyclicBarrier(2);
    CyclicBarrier cyclicBarrier1 = new CyclicBarrier(2);
    @Override
    public void run() {
        /** 最开始先把下标 0 的位置赋值为 true */
        marked[index] = true;
        for (int i = 0; i < 10000; i++) {
            total.incrementAndGet();
            try {
                cyclicBarrier1.reset();
                /** 等待 t0、t1 都到位了才开始执行 */
                cyclicBarrier0.await();
            } catch (InterruptedException e) {
                e.printStackTrace();
            } catch (BrokenBarrierException e) {
                e.printStackTrace();
            }
            index++;
            try {
                cyclicBarrier0.reset();
                /** 等到都执行完了 index++ 才开始执行 */
                cyclicBarrier1.await();
            } catch (InterruptedException e) {
                e.printStackTrace();
            } catch (BrokenBarrierException e) {
                e.printStackTrace();
            }
            synchronized (multiThreadError) {
                /** 不光判断当前位置，还有判断前一个位置 */
                if (marked[index] && marked[index - 1]) {
                    wrongCount.incrementAndGet();
                    System.out.println("线程冲突，错误 index：" + index);
                }
                /**
                 *  当某一个线程将此索引标记为 true，如果正常的情况，下一个线程进来应该执行 index++，
                 *  if 判断肯定为 false，因为正常情况下，赋值 true 是在 if 下面，如果上面的 if
                 *  条件成立，则说明两个线程同时操作了 index
                 */
                marked[index] = true;
            }
        }
    }

    public static void main(String[] args) throws InterruptedException {
        Thread t0 = new Thread(multiThreadError);
        Thread t1 = new Thread(multiThreadError);
        t0.start();
        t1.start();
        t0.join();
        t1.join();
        System.out.println("表面上的结果，num：" + multiThreadError.index);
        System.out.println("一共实际执行的次数：" + total.get());
        System.out.println("发生错误次数：" + wrongCount.get());
    }
}
```

结果：

```java
线程冲突，错误 index：6615
表面上的结果，num：19999
一共实际执行的次数：20000
发生错误次数：1
```

观察以上结果，表面上的结果 + 发生错误次数 = 一共实际执行次数，结果终于对了。

感想：

1. ++ 操作在多线程中真的挺麻烦，太容易出错了
2. 写好多线程的代码需要考虑的点很多，稍微地方不注意，就会被并发钻了空子，造成结果的不准确

